version: '2'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yksysjtsws
      MYSQL_DATABASE: live
      MYSQL_USER: live
      MYSQL_PASSWORD: yksysjtsws
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis

  elasticsearch:
    image: elasticsearch:2.4

  feedss:
    image: hub.c.163.com/tangjun/zplive
    ports:
      - "8188:8188"
    volumes:
      - ./feedss/log:/var/log
      - ./upload:/data/upload/image
    links:
      - mysql
      - redis
      - elasticsearch
      
  elasticsearch-jdbc:
    image: hub.c.163.com/tangjun/elasticsearch-jdbc
    links:
      - mysql
      - elasticsearch
    tty: true